# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(default='', help_text='类别名', max_length=40, verbose_name='类别名'),
        ),
    ]
